# GitHub funding configuration
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Use a custom link for Buy Me A Coffee

buy_me_a_coffee: BurnOutTrader