[workspace]
members = [
    "crates/bus",
    "crates/provider",
    "crates/engine",
    "crates/tt-types",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.42", features = ["clock", "std", "serde",] }
chrono-tz = "0.10.4"
bytes = "1.10.1"
thiserror = "2.0.17"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "net", "time", "sync", "io-util"] }
tokio-util = { version = "0.7.16", features = ["codec"] }
async-trait = "0.1.89"
once_cell = "1.21.3"
strum_macros = "0.27.2"
serde = {version = "1.0.228", features = ["derive"]}
rust_decimal = { version = "1.38.0", features = ["serde", "default", "macros"] }
rstest = "0.26.1"
ustr = "1.1.0"
rkyv = { version = "0.8.12", features = ["std", "alloc", "bytecheck"] }