[package]
name = "tt-provider"
version = "0.1.0"
edition = "2024"

[lib]
name = "provider"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
ahash = {workspace = true}
tt-types = { path = "../tt-types" }
tokio = {workspace = true}
