[package]
name = "tt-provider"
version = "0.1.0"
edition.workspace = true

[lib]
name = "provider"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
ahash = {workspace = true}
tt-types = { path = "../types" }
dotenvy = { workspace = true }
