[package]
name = "tt-types"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true}
chrono-tz = {workspace = true}
rust_decimal = { workspace = true }
serde = { workspace = true }
strum_macros = {workspace = true}
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }
rkyv = { workspace = true}
futures = "0.3.31"
tokio = { workspace = true }
dashmap = { workspace = true }
ahash = { workspace = true }
lazy_static = {workspace = true}
[features]
default = []

[dev-dependencies]
