[package]
name = "tt-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

tt-provider = { path = "../provider" }
tt-types = { path = "../tt-types" }
tt-bus = { path = "../bus" }
ahash = {workspace = true}

[[bin]]
name = "tt-engine-test_strategy"
path = "bin/test_strategy.rs"
